GET http://localhost:3000/subscribers/

###

GET http://localhost:3000/subscribers/60dab8080051de23102ae56c

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name" : "mark",
    "subscribedToChannel" : "goodfilms"
}

###

DELETE http://localhost:3000/subscribers/60dab8080051de23102ae56c

###

PATCH http://localhost:3000/subscribers/60da1753cecdf42e0c0c14f1
Content-Type: application/json

{
    "name" : "akira"
}